### ISSUE TITLE
Rename bird_card

### ISSUE THREAD

**Issue by Leoname3000** [Leoname3000/bird-almanac#1]
Consider renaming [bird_card.dart](https://github.com/Leoname3000/bird-almanac/blob/master/lib/components/bird_card.dart) to bird_list.dart

**Comment by mSiotniHS** [comment]
No, bird_card.dart is not the list of _cards_, but rather one element of the list. So I don't think it's required to rename

**Comment by Leoname3000** [comment]
_O k a y_, got it
